name: arriba_server
description: An app that's going to be amazing pretty soon.
publish_to: none # Ensure we don't accidentally publish our private code! ;)
environment:
  sdk: '>=2.0.0-dev <3.0.0'
homepage: https://github.com/angel-dart/angel
dependencies:
  angel_auth: ^2.0.0 # Supports stateless authentication via JWT
  angel_auth_oauth2: ^2.0.0
  angel_configuration: ^2.0.0 # Loads application configuration, along with support for .env files.
  angel_cors: ^2.0.0
  angel_framework: ^2.0.0-alpha # The core server library.
  angel_jael: ^2.0.0 # Server-side templating engine
  angel_mongo: ^2.0.0
  angel_production: ^1.0.0-alpha
  angel_proxy: ^2.0.0
  angel_serialize: ^2.0.0
  angel_static: ^2.0.0 # Static file server
  angel_validate: ^2.0.0 # Allows for validation of input data
  angel_websocket: ^2.0.0
  googleapis: ^0.53.0
  googleapis_auth: ^0.2.7
  kilobyte: ^0.2.0
dev_dependencies:
  angel_hot: ^2.0.0 # Hot-reloading support. :)
  angel_serialize_generator: ^2.0.0
  angel_test: ^2.0.0 # Utilities for testing Angel servers.
  build_runner: ^1.0.0
  io: ^0.3.2
  pedantic: ^1.0.0
  test: ^1.0.0
dependency_overrides:
  uuid: ^2.0.0
